INFO:     Started server process [14904]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8900): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/delta_generator.py", line 36, in <module>
    from streamlit import config, cursor, env_util, logger, runtime, type_util, util
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/cursor.py", line 18, in <module>
    from streamlit.runtime.scriptrunner import get_script_run_ctx
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/__init__.py", line 16, in <module>
    from streamlit.runtime.runtime import Runtime as Runtime
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/runtime.py", line 29, in <module>
    from streamlit.proto.BackMsg_pb2 import BackMsg
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/BackMsg_pb2.py", line 14, in <module>
    from streamlit.proto import ClientState_pb2 as streamlit_dot_proto_dot_ClientState__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/ClientState_pb2.py", line 14, in <module>
    from streamlit.proto import WidgetStates_pb2 as streamlit_dot_proto_dot_WidgetStates__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/WidgetStates_pb2.py", line 14, in <module>
    from streamlit.proto import Common_pb2 as streamlit_dot_proto_dot_Common__pb2
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/proto/Common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

  You can now view your Streamlit app in your browser.

  URL: http://www.moqku.co:8901

2023-06-01 22:28:02.124 Uncaught app exception
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/home/victor/workplace/savings/app.py", line 2, in <module>
    import streamlit_authenticator as stauth
ModuleNotFoundError: No module named 'streamlit_authenticator'
  Stopping...
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
Traceback (most recent call last):
  File "/home/victor/.pyenv/versions/persite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victor/.pyenv/versions/workplace/envs/persite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '04_newyork_taxi_fare/api-dir/api'
pyenv: uvicorn: command not found

The `uvicorn' command exists in these Python versions:
  3.8.10/envs/taxifare
  3.8.10/envs/titanic
  taxifare
  titanic

Note: See 'pyenv help global' for tips on allowing both
      python2 and python3 to be found.
Traceback (most recent call last):
  File "/home/victorbonnet/.pyenv/versions/personalsite/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/victorbonnet/.pyenv/versions/3.8.10/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/victorbonnet/.pyenv/versions/3.8.10/envs/personalsite/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/victorbonnet/.pyenv/versions/3.8.10/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '/home/victorbonnet/workspace/taxifare/api'
